// AgentTeam-Memory — © 2026 Matheus Chiodi (MChiodi). MIT w/ Attribution. Forensic watermark: see NOTICE.
// index — regenerate the per-project _index.md (MOC) and the master index.
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import {
  partition, today, ensure, walk, listProjects, parseFM,
} from '../lib.mjs';

const TITLES = {
  decision: 'Decisions', learning: 'Learnings', memory: 'Memories',
  communication: 'Board / Communication', state: 'Agent state', untyped: 'Other',
};
const ORDER = ['decision', 'learning', 'memory', 'communication', 'state', 'untyped'];

export function indexOne(ROOT, project) {
  const p = partition(ROOT, project);
  if (!existsSync(p.base)) return 0;
  const notes = walk(p.base).map((f) => ({ f, ...parseFM(readFileSync(f, 'utf8')) }));
  const byType = {};
  for (const n of notes) (byType[n.fm.type || 'untyped'] ||= []).push(n);
  const out = [
    '---', 'type: index', `project: ${project}`,
    `summary: "MOC for project ${project} (${notes.length} notes)."`,
    `created: ${today()}`, '---', '',
    `# 🧠 Memory Index — ${project}`, '',
    `> Generated by \`memory.mjs index\`. ${notes.length} note(s).`, '',
  ];
  for (const type of [...ORDER, ...Object.keys(byType).filter((x) => !ORDER.includes(x))]) {
    const arr = byType[type];
    if (!arr || !arr.length) continue;
    out.push(`## ${TITLES[type] || type}`, '');
    arr.sort((a, b) => basename(b.f).localeCompare(basename(a.f)));
    for (const n of arr) {
      const tags = Array.isArray(n.fm.tags) ? n.fm.tags : [];
      out.push(`- [[${basename(n.f, '.md')}]]`
        + (n.fm.agent ? ` · _${n.fm.agent}_` : '')
        + (n.fm.summary ? ` — ${n.fm.summary}` : '')
        + (tags.length ? `  \`${tags.join('` `')}\`` : ''));
    }
    out.push('');
  }
  ensure(p.base);
  writeFileSync(p.index, out.join('\n'), 'utf8');
  return notes.length;
}

export function indexMaster(ROOT) {
  const projects = listProjects(ROOT);
  const out = [
    '---', 'type: index',
    'summary: "Master MOC — all memory-team projects."',
    `created: ${today()}`, '---', '',
    '# 🧠 memory-team — Master Index', '',
    `> ${projects.length} project(s). Generated by \`memory.mjs index\`.`, '',
  ];
  for (const proj of projects.sort()) {
    const n = existsSync(partition(ROOT, proj).base) ? walk(partition(ROOT, proj).base).length : 0;
    out.push(`- [${proj}](projects/${proj}/_index.md) — ${n} note(s)`);
  }
  out.push('');
  ensure(ROOT);
  writeFileSync(join(ROOT, '_index.md'), out.join('\n'), 'utf8');
}

export default {
  name: 'index',
  summary: 'Regenerate the per-project _index.md and the master index (--all = every project)',
  usage: 'index [--all]',
  run(ctx) {
    const { ROOT, PROJECT } = ctx;
    ensure(join(ROOT, 'projects'));
    if (ctx.all) {
      let total = 0;
      const projects = listProjects(ROOT);
      for (const proj of projects) total += indexOne(ROOT, proj);
      indexMaster(ROOT);
      return { ok: true, lines: [`indexed ${projects.length} project(s), ${total} notes. Master _index.md updated.`], data: { projects: projects.length, notes: total } };
    }
    const n = indexOne(ROOT, PROJECT);
    indexMaster(ROOT);
    return { ok: true, lines: [`indexed projects/${PROJECT} (${n} notes) + master _index.md.`], data: { project: PROJECT, notes: n } };
  },
};
